#! /bin/sh
hostname -F /etc/hostname
mount -n -t ramfs ramfs /var -o maxsize=104857600
mount -n -t ramfs ramfs /tmp -o maxsize=10485760
mount -n -t sysfs none /sys
mount -n -t ramfs none /dev -o maxsize=10485760
mkdir /var/tmp
mkdir /var/modules
mkdir /var/run
mkdir /var/log

mkdir /boot
mkdir /tools
mkdir /upgrade

mkdir -p /var/ftp/upload
chmod 777 /var/ftp/upload

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mknod -m 666 /dev/ptmx c 5 2 

mkdir -p /dev/shm
mdev -s
mount -a
echo /sbin/mdev > /proc/sys/kernel/hotplug

mkdir -p /lib/modules/$(uname -r)/
#mv /lib/*.ko /lib/modules/$(uname -r)/

#mount -t yaffs2 /dev/mtdblock5 /home/

#xinetd -stayalive -reuse -pidfile /var/run/xinetd.pid

/usr/sbin/telnetd -p 2650

mkdir /os1/
mkdir /os2/
mkdir /data

ubiattach /dev/ubi_ctrl -m 0  
mount -t ubifs /dev/ubi0_0 /os1/
ubiattach /dev/ubi_ctrl -m 1  
mount -t ubifs /dev/ubi1_0 /os2/
ubiattach /dev/ubi_ctrl -m 3  
mount -t ubifs /dev/ubi2_0 /home/
ubiattach /dev/ubi_ctrl -m 4  
mount -t ubifs /dev/ubi3_0 /data/ 


mkdir /home/bin
mkdir /home/cfg
mkdir /data/dat
mkdir /data/ver
sync
#addby zjj


#add by tianzhy
ifconfig lo 127.0.0.1
#/sbin/insmod /usr/bin/wdt.ko


tftp_cliet_ip=192.168.1.1
tftp_server_ip=192.168.1.254
/sbin/ifconfig eth0  ${tftp_cliet_ip}

down_file_name=ht201e_sys

if [ ! -f /home/bin/autorun.sh ] && [ ! -f /home/bin/vtysh ]
then
	cd /data/ver
	tftp -g -r $down_file_name ${tftp_server_ip}

	if [ $? -ne 0 ]
	then 
		echo "No package download ..."
		exit
	fi

	mkdir tmp

	tar zxvf $down_file_name -C /data/ver/tmp

	cd tmp

	ls *_app_* | xargs -i tar -zxvf {} -C /home/bin

	if [ $? -ne 0 ]
	then 
		echo "package uncompressed error..."
		cd ..
		rm tmp -rf
		exit
	fi

	mv * /data/ver

	cd ..
	rm tmp -rf

	echo ""
	echo "sync..."
	sync
	echo "  download applicaion success, reboot system..."
	sleep 1
	reboot

else
	if [ -f /home/bin/autorun.sh ] 
	then
        echo "system running..."
        /bin/chmod 777 /home/bin/autorun.sh
        /bin/sh /home/bin/autorun.sh
	fi
fi


#start user application
#/bin/sh /home/starter.sh


